task_id: 2
log_dir: ./log/mimo
model_dir: ./model/mimo/b32-256-200s
data_dir: 
  - ./dataset/mimo/raw
out_dir: ./dataset/mimo/output
cond_dir: 
  - ./dataset/mimo/cond

# Training params
max_iter: null
batch_size: 8
learning_rate: 1.0e-4
max_grad_norm: null

# Inference params
inference_batch_size: 1
robust_sampling: true

# Data params
sample_rate: 14
extra_dim: [26, 96]
cond_dim: [26, 96]

# Model params
embed_dim: 256
spatial_hidden_dim: 128
tf_hidden_dim: 256
num_heads: 8
num_spatial_block: 16
num_tf_block: 16
dropout: 0.0
mlp_ratio: 4
learn_tfdiff: false

# Diffusion params
signal_diffusion: true
max_step: 200
blur_schedule: !expr ((0.1**2) * np.ones(200)).tolist()
noise_schedule: !expr np.linspace(5e-4, 0.1, 200).tolist()