task_id: 4
log_dir: ./log/modrec
model_dir: ./model/modrec/flexible-cond
data_dir:
  - C:\Users\acnut\Coding\csp_dataset
  - C:\Users\acnut\Coding\csp_dataset\signal_record_C_2023.txt
out_dir: ./dataset/modrec/output

# Training params
max_iter: null
batch_size: 32
learning_rate: 1.0e-3
max_grad_norm: null

# Inference params
inference_batch_size: 1
robust_sampling: true

# Data params
sample_rate: 32768
input_dim: 1
extra_dim: [1]

# Conditioning configuration
conditioning:
  enabled_fields:
    - mod_type  # Required field
    # Comment out fields to disable them:
    #- symbol_period
    #- carrier_offset
    #- excess_bw
    #- snr
  field_configs:
    mod_type:
      type: "categorical"
      values: ["bpsk", "qpsk", "8psk", "dqpsk", "16qam", "64qam", "256qam", "msk"]
      required: true
    symbol_period:
      type: "continuous"
      normalize: true
      required: false
      min_value: 1.0
      max_value: 10.0
    carrier_offset:
      type: "continuous"
      normalize: true
      required: false
      min_value: -500
      max_value: 500
    excess_bw:
      type: "continuous"
      normalize: true
      required: false
      min_value: 0.0
      max_value: 1.0
    snr:
      type: "continuous"
      normalize: true
      required: false
      min_value: -10
      max_value: 30

# Model params
embed_dim: 256
hidden_dim: 256
num_heads: 8
num_block: 32
dropout: 0.0
mlp_ratio: 4
learn_tfdiff: false

# Diffusion params
signal_diffusion: true
max_step: 200
# Gradually increasing blur schedule
blur_schedule: !expr np.linspace(0.001, 0.1, 200).tolist()
# Linear noise schedule
noise_schedule: !expr np.linspace(1e-4, 0.05, 200).tolist()